spring.application.name=SupplyChainTracker

# Database Connection (Oracle XE)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SYSTEM
# inventory_user
# password123
spring.datasource.password=miya99
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true